### ISSUE TITLE
Theme default is now a configuration setting. 

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/php#3]
I'm getting PHP warnings about `theme_default` not being a valid array key. 

Replacing:
```php
    $theme_path = backdrop_get_path('theme', $conf['theme_default']);
```
with
```php
    $theme_default = config_get('system.core', 'theme_default');
    $theme_path = backdrop_get_path('theme', $theme_default);
```
seems to fix the issue for me. PR forthcoming!

**Comment by stpaultim** [comment]
@jenlampton - Sorry, didn't notice this before (or forgot about it if I did notice it earlier). 

I was unable to recreate the PHP warning. BUT, if it solve a problem for you, I'm good with that. It's a simple change.

Merging.
